### ISSUE TITLE
Create splashscreen

### ISSUE THREAD

**Issue by nikedinikedi** [supermemo/Documentation#44]
- [ ] Find someone to create it or create it by yourself @nikedinikedi 
    - [ ] @alexis- to integrate this in SMA

Maybe in this style? This could be an animation where a robot is summoned from a book

![image](https://user-images.githubusercontent.com/51511831/75438192-36d6ca00-5960-11ea-8034-ec18b4368ad7.png)

**Comment by alexis-** [comment]
I think this belongs in SuperMemoAssistant. There's already a ticket for it there.
(what does splashscreen has to do with documentation ?)
